import turtle
t = turtle.Turtle()

def drawHeart(size):
    t.fillcolor("red")
    t.begin_fill()
    t.left(50)
    t.fd(120)
    t.circle(45,200)
    t.lt(221)
    t.circle(45,200)
    t.fd(130)
    t.end_fill()

def drawAi(size):
    t.pensize(20)
    t.left(190)
    t.fd(size)
    t.up()
    t.left(80)
    t.fd(size/8)
    t.down()
    t.left(40)
    t.fd(size/8)
    t.left(50)
    t.up()
    t.fd(size/2)
    t.left(120)
    t.fd(size/10)
    t.down()
    t.fd(size/8)
    t.right(100)
    t.up()
    t.fd(size/2)
    t.right(90)
    t.fd(size/10)
    t.right(40)
    t.down()
    t.fd(size/7)
    t.up()
    t.setheading(180)
    t.fd(size)
    t.setheading(270)
    t.fd(size/3)
    t.down()
    t.fd(size/5)
    t.backward(size/5)
    t.setheading(0)
    t.fd(size)
    t.right(90)
    t.fd(size/5)

    
t.pencolor("red")
t.speed(80)
t.down()
drawAi(120)
turtle.done()
